/* ============================================================
   CABINET MARRAKCHI — data + i18n (FR / AR / Darija Latin)
   ============================================================ */

window.__DATA__ = {
  /* ---------- Projects ---------- */
  projects: [
    // Architecture
    { id: "p1",  mode: "archi", year: "2024", title: "Villa Tangier Bay",          title_ar: "فيلا خليج طنجة",          it: "Bay",
      location: "Tanger — Malabata",      surface: "620 m²",    type: "Villa privée",         type_ar: "فيلا خاصة",
      img: "photos/villa-contemporaine-piscine.jpg",         tags: ["Villa", "Piscine", "Vue mer"] },
    { id: "p2",  mode: "archi", year: "2023", title: "Villa Nocturne",              title_ar: "فيلا الليل",               it: "Nocturne",
      location: "Tanger — Cap Spartel",   surface: "540 m²",    type: "Villa contemporaine",  type_ar: "فيلا معاصرة",
      img: "photos/villa-nocturne.jpg",                         tags: ["Villa", "Jardin", "Bois"] },
    { id: "p3",  mode: "archi", year: "2024", title: "Résidence Cadre",             title_ar: "إقامة الإطار",             it: "Cadre",
      location: "Tanger — Californie",    surface: "480 m²",    type: "Villa familiale",      type_ar: "فيلا عائلية",
      img: "photos/villa-cadre-lumineux.jpg",                   tags: ["Villa", "Lumière", "Végétal"] },
    { id: "p4",  mode: "archi", year: "2022", title: "Maison Duo",                  title_ar: "منزل دو",                  it: "Duo",
      location: "Tanger — Ibéria",        surface: "320 m²",    type: "Villa jumelée",        type_ar: "فيلا مزدوجة",
      img: "photos/villa-moderne-duo.jpg",                      tags: ["Villa", "Contemporain"] },
    { id: "p5",  mode: "archi", year: "2022", title: "Maison Moderne",              title_ar: "البيت الحديث",             it: "Moderne",
      location: "Tanger — Boubana",       surface: "280 m²",    type: "Résidence",            type_ar: "إقامة",
      img: "photos/villa-moderne-entree.jpg",                   tags: ["Résidence"] },
    { id: "p6",  mode: "archi", year: "2023", title: "Écran Végétal",               title_ar: "الواجهة الخضراء",          it: "Végétal",
      location: "Tanger — Centre-ville",  surface: "2 400 m²",  type: "Immeuble mixte",       type_ar: "عمارة",
      img: "photos/immeuble-vegetal.jpg",                       tags: ["Immeuble", "Commerces", "Végétal"] },
    { id: "p7",  mode: "archi", year: "2024", title: "Moucharabieh",                title_ar: "المشربية",                 it: "Moucharabieh",
      location: "Tanger — Ville Nouvelle",surface: "3 100 m²",  type: "Immeuble résidentiel", type_ar: "عمارة سكنية",
      img: "photos/immeuble-moucharabieh.jpg",                  tags: ["Immeuble", "Ornement"] },
    { id: "p8",  mode: "archi", year: "2024", title: "Résidence Classique",         title_ar: "الإقامة الكلاسيكية",       it: "Classique",
      location: "Tanger — Iberia",        surface: "4 800 m²",  type: "Résidence collective", type_ar: "إقامة جماعية",
      img: "photos/residence-classique.jpg",                    tags: ["Résidence"] },
    { id: "p9",  mode: "archi", year: "2023", title: "Villa Jardin",                title_ar: "فيلا الحديقة",             it: "Jardin",
      location: "Tanger — Achakar",       surface: "700 m²",    type: "Villa avec piscine",   type_ar: "فيلا مع مسبح",
      img: "photos/villa-piscine-jardin.jpg",                   tags: ["Villa", "Piscine"] },
    { id: "p10", mode: "archi", year: "2024", title: "Villa Courbes",               title_ar: "فيلا المنحنيات",           it: "Courbes",
      location: "Tanger — Jbel Kbir",     surface: "890 m²",    type: "Villa signature",      type_ar: "فيلا مميزة",
      img: "photos/villa-courbes.jpg",                          tags: ["Villa", "Piscine", "Signature"] },
    { id: "p11", mode: "archi", year: "2024", title: "Villa Courbes — Crépuscule",  title_ar: "فيلا المنحنيات — الغسق",  it: "Crépuscule",
      location: "Tanger — Jbel Kbir",     surface: "890 m²",    type: "Villa signature",      type_ar: "فيلا مميزة",
      img: "photos/villa-contemporaine-piscine-soir.jpg",       tags: ["Villa", "Nocturne"] },
    { id: "p12", mode: "archi", year: "2023", title: "Villa Pierre",                title_ar: "فيلا الحجر",               it: "Pierre",
      location: "Tanger — Cap Malabata",  surface: "650 m²",    type: "Villa familiale",      type_ar: "فيلا عائلية",
      img: "photos/villa-pierre-piscine.jpg",                   tags: ["Villa", "Pierre", "Piscine"] },
    { id: "p13", mode: "archi", year: "2023", title: "Résidence Piscine",           title_ar: "إقامة المسبح",             it: "Piscine",
      location: "Tanger — Nord",          surface: "12 000 m²", type: "Ensemble résidentiel", type_ar: "مجمع سكني",
      img: "photos/residence-piscine-villas.jpg",               tags: ["Résidence", "Loisirs"] },
    { id: "p14", mode: "archi", year: "2024", title: "Résidence Pergola",           title_ar: "إقامة البرغولا",           it: "Pergola",
      location: "Tanger — Ghandouri",     surface: "8 600 m²",  type: "Ensemble de villas",   type_ar: "مجمع فلل",
      img: "photos/residence-pergola.jpg",                      tags: ["Résidence", "Villas"] },
    { id: "p15", mode: "archi", year: "2024", title: "Résidence Bois",              title_ar: "إقامة الخشب",              it: "Bois",
      location: "Tanger — Boukhalef",     surface: "2 200 m²",  type: "Villa témoin",         type_ar: "فيلا نموذجية",
      img: "photos/residence-bois-jaune.jpg",                   tags: ["Villa", "Bois"] },
    { id: "p16", mode: "archi", year: "2024", title: "Résidence Nuit",              title_ar: "إقامة الليل",              it: "Nuit",
      location: "Tanger — Boukhalef",     surface: "14 000 m²", type: "Ensemble urbain",      type_ar: "مجمع حضري",
      img: "photos/residence-rue-nuit.jpg",                     tags: ["Résidence", "Nocturne"] },
    { id: "p17", mode: "archi", year: "2024", title: "Résidence Jour",              title_ar: "إقامة النهار",             it: "Jour",
      location: "Tanger — Boukhalef",     surface: "14 000 m²", type: "Ensemble urbain",      type_ar: "مجمع حضري",
      img: "photos/residence-journee.jpg",                      tags: ["Résidence"] },
    { id: "p18", mode: "archi", year: "2024", title: "Résidence Allée",             title_ar: "إقامة الممر",              it: "Allée",
      location: "Tanger — Centre",        surface: "8 400 m²",  type: "Résidence familiale",  type_ar: "إقامة عائلية",
      img: "photos/residence-allee.jpg",                        tags: ["Résidence", "Vie"] },
    { id: "p19", mode: "archi", year: "2024", title: "Résidence Nocturne",          title_ar: "الإقامة الليلية",          it: "Nocturne",
      location: "Tanger — Malabata",      surface: "22 000 m²", type: "Ensemble mixte",       type_ar: "مجمع مختلط",
      img: "photos/residence-nocturne.jpg",                     tags: ["Immeuble", "Nocturne"] },
    { id: "p20", mode: "archi", year: "2024", title: "Villa n° 15",                 title_ar: "فيلا رقم ١٥",              it: "Quinze",
      location: "Tanger — Le Mirador",    surface: "460 m²",    type: "Villa signature",      type_ar: "فيلا مميزة",
      img: "photos/villa-15-nuit.jpg",                          tags: ["Villa", "Nocturne"] },
    { id: "p21", mode: "archi", year: "2024", title: "Villa Piscine Bois",          title_ar: "فيلا المسبح والخشب",       it: "Bois",
      location: "Tanger — Achakar",       surface: "580 m²",    type: "Villa avec piscine",   type_ar: "فيلا مع مسبح",
      img: "photos/villa-piscine-bois.jpg",                     tags: ["Villa", "Piscine", "Bois"] },

    // Interior
    { id: "i1", mode: "interior", year: "2023", title: "Appartement Double Hauteur", title_ar: "شقة بارتفاع مضاعف", it: "Double Hauteur",
      location: "Tanger — Bord de mer",   surface: "240 m²",  type: "Aménagement résidentiel", type_ar: "تصميم سكني",
      img: "photos/interieur-double-hauteur.jpg",  tags: ["Résidentiel", "Béton", "Double hauteur"] },
    { id: "i2", mode: "interior", year: "2022", title: "Loft Pop",                  title_ar: "لوفت بوب",               it: "Loft",
      location: "Tanger — Ville Haute",   surface: "180 m²",  type: "Loft privé",              type_ar: "لوفت خاص",
      img: "photos/interieur-salon-beton.jpg",     tags: ["Loft", "Art", "Béton"] },
    { id: "i3", mode: "interior", year: "2023", title: "Chambre Orientale",         title_ar: "الغرفة الشرقية",         it: "Orientale",
      location: "Tanger — Riad",          surface: "48 m²",   type: "Suite maître",            type_ar: "جناح رئيسي",
      img: "photos/interieur-chambre-orientale.jpg", tags: ["Chambre", "Artisanat"] },
    { id: "i4", mode: "interior", year: "2023", title: "Salon Marocain",            title_ar: "الصالون المغربي",        it: "Marocain",
      location: "Tanger — Villa privée",  surface: "90 m²",   type: "Salon de réception",      type_ar: "صالون استقبال",
      img: "photos/interieur-salon-marocain.jpg",  tags: ["Salon", "Tradition"] },
  ],

  /* ---------- Before / After ---------- */
  beforeAfter: [
    { title: "Villa Malabata — rénovation complète",
      title_ar: "فيلا مالاباطا — ترميم كامل",
      before: "photos/villa-moderne-entree.jpg",
      after:  "photos/villa-moderne-duo.jpg" },
  ],

  /* ---------- Timeline ---------- */
  timeline: [
    { year: "1998",
      title:    "Fondation à Tanger",
      title_ar: "تأسيس المكتب في طنجة",
      desc:    "Ouverture du cabinet rue de Fès. Premier projet livré : une villa familiale à Iberia, 380 m². Le début d'une histoire avec le Nord du Maroc.",
      desc_ar: "افتتاح المكتب بشارع فاس. أول مشروع: فيلا عائلية بإبيريا، 380 م². بداية القصة مع شمال المغرب." },
    { year: "2004",
      title:    "Diversification — industrie & tertiaire",
      title_ar: "التنويع — الصناعة والتجارة",
      desc:    "Tanger Free Zone s'ouvre. Le cabinet intègre les bâtiments industriels, entrepôts logistiques et équipements tertiaires à son offre.",
      desc_ar: "افتتاح منطقة طنجة الحرة. يضم المكتب المباني الصناعية والمستودعات اللوجستية والمرافق التجارية إلى خدماته." },
    { year: "2010",
      title:    "Équipements publics & éducatifs",
      title_ar: "المرافق العامة والتعليمية",
      desc:    "Premières écoles, lycées et cliniques conçus par le cabinet. 12 établissements livrés dans la région TTA en six ans.",
      desc_ar: "أول مدارس وثانويات وعيادات يصممها المكتب. 12 مؤسسة تسليم في منطقة طنجة تطوان الحسيمة خلال ست سنوات." },
    { year: "2012",
      title:    "Architecture d'intérieur",
      title_ar: "الهندسة الداخلية",
      desc:    "Création du pôle intérieur. Riads, suites hôtelières, lofts contemporains et salons de réception sur-mesure à travers le Maroc.",
      desc_ar: "إنشاء قطب التصميم الداخلي. رياضات وأجنحة فندقية ولوفتات معاصرة وصالونات استقبال مخصصة في أنحاء المغرب." },
    { year: "2018",
      title:    "300 projets — une génération",
      title_ar: "300 مشروع — جيل كامل",
      desc:    "Le cabinet franchit les 300 réalisations livrées. Villas, immeubles, usines, écoles — vingt ans d'une pratique totale de l'architecture au Maroc.",
      desc_ar: "يتجاوز المكتب 300 مشروع منجز. فلل، عمارات، مصانع، مدارس — عشرون سنة من الممارسة الشاملة للعمارة في المغرب." },
    { year: "2026",
      title:    "Nouvelle ère — digital & MRE",
      title_ar: "عصر جديد — رقمي والمغاربة في الخارج",
      desc:    "Suivi de chantier en temps réel, coordination à distance, clients dans 8 pays. Le cabinet entre dans son prochain chapitre, sans perdre son ADN tangerois.",
      desc_ar: "متابعة الأشغال في الوقت الحقيقي، تنسيق عن بُعد، عملاء في 8 دول. يدخل المكتب فصله الجديد دون أن يفقد هويته الطنجاوية." },
  ],
};

/* ================================================================
   TRANSLATIONS — FR / AR / Darija Latin
   ================================================================ */
window.__I18N__ = {

  /* ============================================================ FRANÇAIS */
  fr: {
    nav: {
      work: "Projets", expertises: "Expertises", investir: "Investir à Tanger",
      mre: "MRE", about: "Agence", contact: "Contact", rdv: "Prendre RDV"
    },
    hero: {
      eyebrow: "MK Architects · D.P.L.G. · Tanger, Maroc · Depuis 1998",
      title_l1: "Votre partenaire",
      title_l2: "pour tous vos projets",
      title_l3: "immobiliers à",
      title_l4: "Tanger.",
      sub: "Architecture résidentielle, industrielle & tertiaire. 30 ans d'exercice. 340+ projets livrés.",
      scroll: "Découvrir",
      counter: (i, n) => `${String(i).padStart(2,"0")} / ${String(n).padStart(2,"0")}`,
    },
    split: {
      num_archi: "Volet 01", num_int: "Volet 02",
      archi: "Architecture", interior: "Architecture d'intérieur", arrow: "Voir →",
    },
    manifesto: {
      eyebrow: "Notre philosophie",
      p1: React.createElement(React.Fragment, null,
        "Trente ans. 340 projets. Des villas aux ",
        React.createElement("i", {className:"it"}, "usines"),
        ", des riads aux ",
        React.createElement("i", {className:"it"}, "établissements scolaires"),
        " — chaque espace que nous concevons témoigne d'une pratique totale de l'architecture au Maroc du Nord."
      ),
      p2: React.createElement(React.Fragment, null,
        "Notre force : maîtriser ",
        React.createElement("i", {className:"it"}, "l'intégralité du cycle"),
        ". Esquisse, permis, exécution, réception des travaux — un seul interlocuteur, du premier trait au dernier carrelage."
      ),
      p3: React.createElement(React.Fragment, null,
        "Que vous soyez à Tanger ou à Paris, à Bruxelles ou à Montréal — votre projet ",
        React.createElement("i", {className:"it"}, "avance"),
        ", documenté et suivi en temps réel par une équipe que les familles tangeroise font confiance depuis une génération."
      ),
      sig: "— MK Architects, Architecte D.P.L.G. · Tanger.",
    },
    stats: [
      { n: 30,    label: "Ans d'exercice",          suffix: "" },
      { n: 340,   label: "Projets livrés",           suffix: "+" },
      { n: 220000,label: "M² construits",            suffix: "+" },
      { n: 18,    label: "Typologies architecturales",suffix: "" },
    ],
    strip: {
      title_1: "Projets",
      title_2: "récents",
      meta: "Une sélection de réalisations 2022 — 2024. Villas, résidences collectives, équipements à travers le Royaume.",
    },
    gallery: {
      title_1: "Toutes",
      title_2: "les réalisations",
      filters: { all: "Tout", archi: "Architecture", interior: "Intérieur", villa: "Villas", residence: "Résidences" },
      meta: "Explorez nos 25+ projets. Cliquez pour agrandir.",
    },
    ba: {
      title_1: "Avant",
      title_2: "Après",
      meta: "Glissez le curseur. Certaines transformations parlent plus que mille plans.",
    },
    timeline: {
      title_1: "Trente",
      title_2: "années",
      meta: "Six jalons qui ont façonné le cabinet.",
    },
    ticker: ["Tanger", "Casablanca", "Rabat", "Marrakech", "Fès", "Tétouan",
             "Paris", "Bruxelles", "Lyon", "Amsterdam", "Montréal", "Dubaï", "Madrid", "Assilah"],

    /* ── Marché tangerois ── */
    market: {
      eyebrow: "Le marché immobilier tangerois",
      title_1: "Investir à Tanger :",
      title_2: "les chiffres parlent.",
      desc: "Tanger est la ville la plus dynamique du Maghreb. Premier port d'Afrique et de Méditerranée, hub industriel mondial, croissance démographique soutenue — les fondamentaux immobiliers sont exceptionnels et la tendance s'accélère.",
      highlights: [
        { n: "+43 %", label: "Hausse des prix résidentiels — Tanger 2021–2024" },
        { n: "115 Mrd",label: "MAD transférés par les MRE vers le Maroc en 2023" },
        { n: "N° 1",   label: "Port de conteneurs d'Afrique & Méditerranée" },
        { n: "1 000+", label: "Entreprises internationales — Tanger Free Zone" },
      ],
      chart1_title: "Évolution du prix au m² résidentiel",
      chart1_sub:   "Tanger — zones prime (Malabata, Californie, Cap Spartel)",
      chart1_source:"Source : ANCFCC · Indice des Prix des Actifs Immobiliers (IPAI), Bank Al-Maghrib",
      chart2_title: "Transferts des MRE vers le Maroc",
      chart2_sub:   "Milliards de dirhams — 2019 à 2023",
      chart2_source:"Source : Bank Al-Maghrib, Rapport annuel 2023",
      sources: "Sources & références : Bank Al-Maghrib (IPAI, Rapports annuels 2019–2023) · Agence Nationale de la Conservation Foncière, du Cadastre et de la Cartographie (ANCFCC) · Haut-Commissariat au Plan (HCP) · Centre Régional d'Investissement Tanger-Tétouan-Al Hoceima (CRI TTA) · Tanger Med Port Authority · Ministère de l'Industrie et du Commerce, Maroc.",
    },

    /* ── Section MRE ── */
    mre: {
      eyebrow: "Marocains Résidant à l'Étranger",
      title_1: "Votre maison à Tanger.",
      title_2: "Vous, partout ailleurs.",
      desc: "Vous vivez en France, en Belgique, aux Pays-Bas, au Canada ou dans le Golfe. Votre projet immobilier à Tanger mérite un partenaire de confiance qui le pilote de A à Z — sans que vous ayez à traverser la Méditerranée à chaque réunion de chantier.",
      stat1_n: "45+", stat1_l: "Projets livrés pour des clients MRE",
      stat2_n: "8",   stat2_l: "Pays de résidence de nos clients",
      stat3_n: "48h", stat3_l: "Délai de réponse garanti",
      cards: [
        { num:"01", title: "Suivi photo & vidéo hebdomadaire",
          desc: "Compte-rendu illustré chaque semaine : photos du chantier, vidéos des avancées, état d'avancement par lot. Vous voyez chaque étape comme si vous y étiez." },
        { num:"02", title: "Interlocuteur unique, toujours joignable",
          desc: "Un architecte référent dédié à votre projet. Groupe WhatsApp, appels vidéo, email — en français, arabe ou darija. Fini les intermédiaires qui se renvoient la balle." },
        { num:"03", title: "Gestion complète de A à Z",
          desc: "Permis de construire, sélection des entreprises, suivi des corps d'état, contrôle qualité, réception des travaux. Vous validez les étapes clés, nous gérons le reste." },
        { num:"04", title: "Décaissements par jalons certifiés",
          desc: "Votre argent ne sort que sur preuve photographique et documentée d'avancement réel. Aucun paiement anticipé non justifié. Transparence totale." },
        { num:"05", title: "Coordination notariale & bancaire",
          desc: "Nous travaillons avec votre notaire et votre banque à Tanger. Transferts de fonds, hypothèques, actes — nous vous guidons dans chaque démarche administrative." },
        { num:"06", title: "Remise des clés clé en main",
          desc: "Vous posez votre valise dans une maison finie, nettoyée, documentée plan par plan. Garantie décennale. Assistance post-livraison incluse la première année." },
      ],
      cta: "Je suis MRE — parlons de mon projet",
    },

    /* ── Expertises ── */
    expertises: {
      eyebrow: "Nos expertises",
      title_1: "Trois expertises.",
      title_2: "Une seule adresse.",
      intro: "Architecture, design d'intérieur, conseil immobilier — tout ce dont vous avez besoin pour concrétiser votre projet au Maroc, sans mauvaise surprise, piloté par un cabinet indépendant qui maîtrise chaque dimension du métier depuis 30 ans.",
      items: [
        {
          num: "01",
          title: "Architecture",
          sub: "Résidentiel · Industriel · Tertiaire · Équipements publics",
          desc: "Villas privées, complexes résidentiels, bâtiments industriels, établissements scolaires, hôtels, immeubles de bureaux. Du premier trait au dernier carrelage — un seul cabinet, une seule responsabilité.",
          services: [
            "Avant-projets sommaires & définitifs",
            "Plans d'exécution tous corps d'état",
            "Constitution du dossier de permis",
            "Sélection & coordination des entreprises",
            "Contrôle qualité & suivi de chantier",
            "Réception des travaux",
          ],
          cta: "Voir les projets →",
          href: "#projets",
          highlight: false,
        },
        {
          num: "02",
          title: "Architecture d'intérieur",
          sub: "Sur mesure · Rénovation · Vie & espaces professionnels",
          desc: "Riads, duplex contemporains, lofts, suites hôtelières, salons de réception, showrooms. Nous concevons des intérieurs qui révèlent l'identité de leurs habitants et traversent les modes.",
          services: [
            "Conception & plans d'aménagement",
            "Choix matériaux, revêtements & mobilier",
            "Rénovation & transformation complète",
            "Suivi des travaux d'aménagement",
            "Mise en scène & coordination déco finale",
          ],
          cta: "Voir les intérieurs →",
          href: "#interieur",
          highlight: false,
        },
        {
          num: "03",
          title: "Conseil & Accompagnement immobilier",
          sub: "Achat · Faisabilité · Rendement · Maîtrise d'ouvrage déléguée",
          desc: React.createElement(React.Fragment, null,
            "Vous avez trouvé un terrain. On vous a soumis un devis. Mais est-ce le bon emplacement, le bon prix, le bon constructeur ? Construire ou investir au Maroc implique des démarches complexes — réglementation locale, normes de construction, pratiques du secteur. ",
            React.createElement("strong", null, "Depuis 30 ans, nous connaissons le terrain, littéralement."),
            " Notre rôle : vous éviter les erreurs coûteuses et maximiser votre investissement."
          ),
          services: [
            "Due diligence & analyse du terrain (titre foncier, COS, plan d'aménagement)",
            "Étude de faisabilité architecturale & estimation budgétaire indépendante",
            "Conseil en investissement locatif & simulation de rendement",
            "Assistance à la maîtrise d'ouvrage (sélection, validation des devis, contrôle)",
            "Navigation administrative : permis, CTC, ONEE, réceptions provisoire/définitive",
            "Évaluation de biens existants & diagnostic technique avant acquisition",
          ],
          cta: "Parler de mon projet →",
          href: "#rdv",
          highlight: true,
        },
      ],
    },

    /* ── RDV ── */
    rdv: {
      eyebrow: "Prendre rendez-vous",
      title_1: "Parlons de",
      title_2: "votre projet.",
      desc: "Une première rencontre, libre et confidentielle. Remplissez le formulaire — nous vous recontactons sous 48h, y compris si vous êtes à l'étranger.",
      contact: { address: "Tanger, Maroc", phone: "+212 6 XX XX XX XX", email: "contact@cabinet-marrakchi.ma", hours: "Lun — Ven, 9h–18h" },
      addr_k: "Adresse", phone_k: "Téléphone", email_k: "E-mail", hours_k: "Horaires",
      steps: ["Type", "Nature", "Contact", "Date", "Message"],
      step_count: (i, n) => `Étape ${i} / ${n}`,
      s1_title_1: "Quel type de", s1_title_2: "projet ?",
      s1_sub: "Un seul choix. Vous pourrez préciser à l'étape suivante.",
      s1_opts: [
        { k: "archi",    label: "Architecture neuve",         hint: "Construction neuve" },
        { k: "interior", label: "Architecture d'intérieur",   hint: "Aménagement" },
        { k: "both",     label: "Les deux",                   hint: "Projet complet" },
        { k: "reno",     label: "Rénovation / extension",     hint: "Existant" },
      ],
      s2_title_1: "Nature du", s2_title_2: "projet ?",
      s2_sub: "Pour mieux préparer notre échange.",
      s2_opts: [
        { k: "villa",      label: "Villa / maison individuelle", hint: "Résidentiel" },
        { k: "residence",  label: "Résidence / ensemble",        hint: "Collectif" },
        { k: "industriel", label: "Bâtiment industriel",         hint: "Usine, entrepôt, zone" },
        { k: "equipement", label: "Équipement public",           hint: "École, clinique, hôtel" },
        { k: "bureau",     label: "Bureau / tertiaire",          hint: "Professionnel" },
        { k: "autre",      label: "Autre",                       hint: "À préciser" },
      ],
      s3_title_1: "Qui êtes-", s3_title_2: "vous ?",
      s3_sub: "Confidentiel. Utilisé uniquement pour cette demande.",
      f_name: "Nom complet", f_email: "E-mail", f_phone: "Téléphone",
      s4_title_1: "Quand vous", s4_title_2: "rencontrer ?",
      s4_sub: "Choisissez une date. Nous confirmons le créneau exact par retour.",
      days: ["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],
      months: ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],
      s5_title_1: "Un mot pour", s5_title_2: "finir ?",
      s5_sub: "Budget, inspirations, contraintes, calendrier. Tout est utile.",
      f_msg: "Votre message (optionnel)",
      recap: "Récapitulatif",
      r_type: "Type", r_nature: "Nature", r_contact: "Contact", r_date: "Date", r_msg: "Message",
      btn_next: "Suivant", btn_back: "Retour", btn_submit: "Envoyer la demande",
      success_t1: "Merci,", success_t2: "à très vite.",
      success_p: "Votre demande a bien été reçue. Nous vous recontactons sous 48 heures — depuis Tanger ou depuis chez vous.",
      success_mark: "✓",
      none: "—",
    },
    footer: {
      title: "MK Architects — Tanger",
      desc: "Architecte D.P.L.G. · Membre du Conseil de l'Ordre National des Architectes du Maroc · Fondé en 1998.",
      col1: "Agence",    col1_links: ["Manifeste", "Philosophie", "Timeline", "Contact"],
      col2: "Expertises",col2_links: ["Villas & résidences", "Ensembles résidentiels", "Bâtiments industriels", "Équipements publics", "Architecture d'intérieur"],
      col3: "Suivre",    col3_links: ["Instagram", "LinkedIn", "Pinterest", "Behance"],
      copyright: "© 2026 MK Architects. Tous droits réservés.",
      credit: "Fondé en 1998 · Tanger, Maroc",
    },
  },

  /* ============================================================ ARABE */
  ar: {
    nav: { work: "المشاريع", expertises: "خدماتنا", investir: "الاستثمار بطنجة", mre: "المغاربة في الخارج", about: "المكتب", contact: "اتصال", rdv: "حجز موعد" },
    hero: {
      eyebrow: "MK Architects · دبلوم دولة · طنجة",
      title_l1: "شريككم في",
      title_l2: "مشاريعكم العقارية",
      title_l3: "في",
      title_l4: "طنجة.",
      sub: "هندسة معمارية سكنية وصناعية وتجارية. 30 سنة من الممارسة، 340+ مشروع.",
      scroll: "اكتشف",
      counter: (i, n) => `${String(i).padStart(2,"0")} / ${String(n).padStart(2,"0")}`,
    },
    split: { num_archi: "القسم 01", num_int: "القسم 02", archi: "الهندسة المعمارية", interior: "التصميم الداخلي", arrow: "← عرض" },
    manifesto: {
      eyebrow: "فلسفتنا",
      p1: React.createElement(React.Fragment, null,
        "ثلاثون سنة. 340 مشروعاً. من الفلل إلى ",
        React.createElement("i", {className:"it"}, "المصانع"),
        "، من الرياض إلى ",
        React.createElement("i", {className:"it"}, "المؤسسات التعليمية"),
        " — كل فضاء نصممه يشهد على ممارسة شاملة للعمارة في شمال المغرب."
      ),
      p2: React.createElement(React.Fragment, null,
        "قوتنا : إتقان ",
        React.createElement("i", {className:"it"}, "كامل الدورة"),
        ". التصميم، رخصة البناء، التنفيذ، الاستلام — محاور واحد من الرسم الأول إلى آخر تشطيب."
      ),
      p3: React.createElement(React.Fragment, null,
        "سواء كنتم في طنجة أو باريس، في بروكسيل أو مونتريال — مشروعكم ",
        React.createElement("i", {className:"it"}, "يتقدم"),
        "، موثقاً ومتابعاً في الوقت الحقيقي من فريق يثق به أبناء طنجة منذ جيل."
      ),
      sig: "— MK Architects، مهندس معماري · طنجة.",
    },
    stats: [
      { n: 30,    label: "سنة من الممارسة",           suffix: "" },
      { n: 340,   label: "مشروع منجز",                suffix: "+" },
      { n: 220000,label: "متر مربع مبني",              suffix: "+" },
      { n: 18,    label: "تخصصاً معمارياً",            suffix: "" },
    ],
    strip: { title_1: "مشاريع", title_2: "حديثة", meta: "مختارات من إنجازات 2022 — 2024 عبر المملكة." },
    gallery: {
      title_1: "كل", title_2: "الإنجازات",
      filters: { all: "الكل", archi: "معمارية", interior: "داخلية", villa: "فلل", residence: "إقامات" },
      meta: "أكثر من 25 مشروعاً. انقر للتكبير.",
    },
    ba: { title_1: "قبل", title_2: "بعد", meta: "حرّك المؤشر. بعض التحوّلات تتجاوز الكلام." },
    timeline: { title_1: "ثلاثون", title_2: "سنة", meta: "ستة محطات شكّلت مسار المكتب." },
    ticker: ["طنجة", "الدار البيضاء", "الرباط", "مراكش", "فاس", "تطوان", "باريس", "بروكسيل", "أمستردام", "مونتريال", "دبي", "مدريد", "أصيلة"],
    market: {
      eyebrow: "سوق العقار الطنجاوي",
      title_1: "الاستثمار في طنجة :",
      title_2: "الأرقام تتكلم.",
      desc: "طنجة هي المدينة الأكثر ديناميكية في المغرب العربي. أول ميناء في أفريقيا والبحر الأبيض المتوسط، قطب صناعي عالمي، نمو ديموغرافي متواصل — الأساسيات العقارية استثنائية والاتجاه يتسارع.",
      highlights: [
        { n: "+43 %", label: "ارتفاع أسعار السكن — طنجة 2021–2024" },
        { n: "115 مليار",label: "درهم حوّلها المغاربة في الخارج عام 2023" },
        { n: "الأول",    label: "ميناء الحاويات في أفريقيا والمتوسط" },
        { n: "+1000",    label: "شركة دولية في المنطقة الحرة بطنجة" },
      ],
      chart1_title: "تطور سعر المتر المربع السكني",
      chart1_sub:   "طنجة — المناطق الراقية (مالاباطا، كاليفورنيا، كاب سبارتيل)",
      chart1_source:"المصدر: ANCFCC · مؤشر أسعار الأصول العقارية، بنك المغرب",
      chart2_title: "تحويلات المغاربة المقيمين بالخارج",
      chart2_sub:   "مليارات الدراهم — 2019 إلى 2023",
      chart2_source:"المصدر: بنك المغرب، التقرير السنوي 2023",
      sources: "المصادر: بنك المغرب (مؤشر IPAI، التقارير السنوية 2019–2023) · الوكالة الوطنية للمحافظة العقارية (ANCFCC) · المندوبية السامية للتخطيط (HCP) · مركز الاستثمار الجهوي طنجة تطوان الحسيمة · ميناء طنجة المتوسط · وزارة الصناعة والتجارة.",
    },
    mre: {
      eyebrow: "المغاربة المقيمون في الخارج",
      title_1: "منزلكم في طنجة.",
      title_2: "وأنتم في كل مكان.",
      desc: "تعيشون في فرنسا أو بلجيكا أو هولندا أو كندا أو الخليج. مشروعكم العقاري في طنجة يستحق شريكاً موثوقاً يديره من الألف إلى الياء — دون أن تضطروا إلى عبور البحر في كل اجتماع ورش.",
      stat1_n: "+45", stat1_l: "مشروعاً منجزاً لعملاء مغاربة الخارج",
      stat2_n: "8",   stat2_l: "دول إقامة لعملائنا",
      stat3_n: "48 س",stat3_l: "وقت الاستجابة المضمون",
      cards: [
        { num:"01", title: "متابعة أسبوعية بالصور والفيديو",
          desc: "تقرير مصوّر كل أسبوع: صور الورشة، مقاطع الفيديو، تقدم كل بند. ترون كل مرحلة كأنكم حاضرون." },
        { num:"02", title: "محاور واحد دائم التواصل",
          desc: "مهندس مرجعي مخصص لمشروعكم. واتساب، مكالمات فيديو، بريد إلكتروني — بالفرنسية أو العربية أو الدارجة." },
        { num:"03", title: "إدارة شاملة من الألف إلى الياء",
          desc: "رخصة البناء، اختيار المقاولين، متابعة الأشغال، مراقبة الجودة، استلام الأعمال. أنتم تعتمدون المراحل الأساسية ونحن ندير الباقي." },
        { num:"04", title: "صرف بالأقساط الموثقة",
          desc: "لا يخرج مالكم إلا بدليل مصوّر وموثق على التقدم الفعلي. لا مدفوعات مسبقة غير مبررة. شفافية تامة." },
        { num:"05", title: "تنسيق توثيقي ومصرفي",
          desc: "نتعاون مع موثقكم وبنككم في طنجة. تحويلات، رهون، عقود — نرشدكم في كل خطوة إدارية." },
        { num:"06", title: "تسليم مفتاح بيد",
          desc: "تضعون حقيبتكم في منزل جاهز، نظيف، موثق مخططاً مخططاً. ضمان عشري. مرافقة ما بعد التسليم مشمولة للسنة الأولى." },
      ],
      cta: "أنا مغترب — لنتحدث عن مشروعي",
    },

    /* ── Expertises AR ── */
    expertises: {
      eyebrow: "خدماتنا",
      title_1: "ثلاثة تخصصات.",
      title_2: "عنوان واحد.",
      intro: "هندسة معمارية، تصميم داخلي، استشارة عقارية — كل ما تحتاجه لإنجاز مشروعك في المغرب، بدون مفاجآت، تحت إشراف مكتب مستقل يتقن كل أبعاد المهنة منذ 30 سنة.",
      items: [
        {
          num: "01",
          title: "الهندسة المعمارية",
          sub: "سكني · صناعي · تجاري · مرافق عامة",
          desc: "فلل خاصة، مجمعات سكنية، مبانٍ صناعية، مؤسسات تعليمية، فنادق، مبانٍ إدارية. من أول خط إلى آخر تشطيب — مكتب واحد، مسؤولية واحدة.",
          services: [
            "مشاريع أولية ونهائية",
            "مخططات التنفيذ لجميع الأعمال",
            "ملف رخصة البناء",
            "اختيار المقاولين وتنسيق الأعمال",
            "مراقبة الجودة ومتابعة الأشغال",
            "استلام الأعمال",
          ],
          cta: "عرض المشاريع →",
          href: "#projets",
          highlight: false,
        },
        {
          num: "02",
          title: "التصميم الداخلي",
          sub: "على القياس · تجديد · مساحات سكنية ومهنية",
          desc: "رياضات، دوبلكسات معاصرة، لوفتات، أجنحة فندقية، صالونات استقبال، معارض. نصمم مساحات داخلية تعكس هوية أصحابها وتصمد أمام الزمن.",
          services: [
            "تصميم وخطط التهيئة",
            "اختيار المواد والأسطح والأثاث",
            "التجديد والتحويل الكامل",
            "متابعة أعمال التهيئة",
            "الديكور النهائي والإعداد",
          ],
          cta: "عرض التصاميم الداخلية →",
          href: "#interieur",
          highlight: false,
        },
        {
          num: "03",
          title: "الاستشارة والمرافقة العقارية",
          sub: "شراء · جدوى · مردودية · إدارة المشروع",
          desc: React.createElement(React.Fragment, null,
            "عثرتم على قطعة أرض. قُدِّم لكم عرض. لكن هل هو الموقع المناسب، السعر الصحيح، المقاول الموثوق؟ البناء أو الاستثمار في المغرب يستلزم إجراءات معقدة. ",
            React.createElement("strong", null, "منذ 30 سنة نعرف الميدان حرفياً."),
            " دورنا: تجنيبكم الأخطاء المكلفة وتعظيم استثماركم."
          ),
          services: [
            "العناية الواجبة وتحليل الأرض (الرسم العقاري، معاملات البناء، المخطط التوجيهي)",
            "دراسة الجدوى المعمارية وتقدير الميزانية المستقل",
            "الاستشارة في الاستثمار الإيجاري وتحليل المردودية",
            "مساعدة صاحب المشروع (اختيار المقاولين، التحقق من العروض، المراقبة)",
            "المرافقة الإدارية: الرخص، CTC، الاستلامات",
            "تقييم العقارات القائمة والتشخيص التقني قبل الاقتناء",
          ],
          cta: "التحدث عن مشروعي →",
          href: "#rdv",
          highlight: true,
        },
      ],
    },

    rdv: {
      eyebrow: "أخذ موعد",
      title_1: "لنتحدث عن",
      title_2: "مشروعك.",
      desc: "لقاء أول، حر وسري. املأ النموذج وسنتصل بك خلال 48 ساعة، سواء كنت في المغرب أو في الخارج.",
      contact: { address: "طنجة، المغرب", phone: "+212 6 XX XX XX XX", email: "contact@cabinet-marrakchi.ma", hours: "الإثنين — الجمعة، 9ص–6م" },
      addr_k: "العنوان", phone_k: "هاتف", email_k: "بريد", hours_k: "ساعات",
      steps: ["النوع", "الطبيعة", "التواصل", "التاريخ", "الرسالة"],
      step_count: (i, n) => `المرحلة ${i} / ${n}`,
      s1_title_1: "ما نوع", s1_title_2: "مشروعك؟", s1_sub: "اختيار واحد.",
      s1_opts: [
        { k: "archi",    label: "هندسة معمارية",  hint: "بناء جديد" },
        { k: "interior", label: "تصميم داخلي",    hint: "تهيئة" },
        { k: "both",     label: "الاثنان معاً",   hint: "مشروع كامل" },
        { k: "reno",     label: "ترميم / توسعة",  hint: "قائم" },
      ],
      s2_title_1: "طبيعة", s2_title_2: "المشروع؟", s2_sub: "لتحضير لقائنا.",
      s2_opts: [
        { k: "villa",      label: "فيلا / مسكن",      hint: "سكني" },
        { k: "residence",  label: "إقامة / مجمع",      hint: "جماعي" },
        { k: "industriel", label: "مبنى صناعي",        hint: "مصنع، مستودع" },
        { k: "equipement", label: "مرفق عام",           hint: "مدرسة، عيادة، فندق" },
        { k: "bureau",     label: "مكاتب / تجارة",     hint: "مهني" },
        { k: "autre",      label: "آخر",               hint: "يحدد" },
      ],
      s3_title_1: "من", s3_title_2: "أنت؟", s3_sub: "سري، لهذا الطلب فقط.",
      f_name: "الاسم الكامل", f_email: "البريد", f_phone: "الهاتف",
      s4_title_1: "متى", s4_title_2: "نلتقي؟", s4_sub: "اختر تاريخاً، سنؤكد الساعة.",
      days: ["إث","ثل","أر","خم","جم","سب","أح"],
      months: ["يناير","فبراير","مارس","أبريل","ماي","يونيو","يوليوز","غشت","شتنبر","أكتوبر","نونبر","دجنبر"],
      s5_title_1: "كلمة", s5_title_2: "أخيرة؟", s5_sub: "إلهام، إكراهات، رغبات. كل شيء مفيد.",
      f_msg: "رسالتك (اختياري)",
      recap: "ملخص", r_type: "النوع", r_nature: "الطبيعة", r_contact: "التواصل", r_date: "التاريخ", r_msg: "الرسالة",
      btn_next: "التالي", btn_back: "عودة", btn_submit: "إرسال الطلب",
      success_t1: "شكراً لك،", success_t2: "نلتقي قريباً.",
      success_p: "تم استلام طلبك. سنتواصل معك خلال 48 ساعة — من المغرب أو من الخارج.",
      success_mark: "✓", none: "—",
    },
    footer: {
      title: "MK Architects — طنجة",
      desc: "مهندس معماري · عضو الهيئة الوطنية للمهندسين المعماريين بالمغرب · تأسس 1998.",
      col1: "المكتب",    col1_links: ["البيان", "الفلسفة", "التاريخ", "التواصل"],
      col2: "الخدمات",   col2_links: ["الفلل والمساكن", "المجمعات السكنية", "المباني الصناعية", "المرافق العامة", "التصميم الداخلي"],
      col3: "متابعة",    col3_links: ["إنستغرام", "لينكدإن", "بنترست", "بيهانس"],
      copyright: "© 2026 MK Architects. جميع الحقوق محفوظة.",
      credit: "تأسس عام 1998 · طنجة، المغرب",
    },
  },

  /* ============================================================ DARIJA */
  dr: {
    nav: { work: "Lkhdma", expertises: "Khadamat", investir: "Lstithmar f Tanja", mre: "MRE", about: "Lmakatib", contact: "Contact", rdv: "Akhd Mawed" },
    hero: {
      eyebrow: "MK Architects — Mohandes M3mari — Tanja — Mn 1998",
      title_l1: "Sharik dyalek",
      title_l2: "f kull mashrou3",
      title_l3: "3qari f",
      title_l4: "Tanja.",
      sub: "Handasa skaniya, sina3iya w tijariya. 30 3am f lkhdma, 340+ mashrou3.",
      scroll: "Zed l taht",
      counter: (i, n) => `${String(i).padStart(2,"0")} / ${String(n).padStart(2,"0")}`,
    },
    split: { num_archi: "Bab 01", num_int: "Bab 02", archi: "Handasa", interior: "Dakhli", arrow: "Chof →" },
    manifesto: {
      eyebrow: "Lfikra dyalna",
      p1: React.createElement(React.Fragment, null,
        "Tlatin 3am. 340 mashrou3. Mn villa hetta ",
        React.createElement("i", {className:"it"}, "usine"),
        ", mn riyad hetta ",
        React.createElement("i", {className:"it"}, "mdrassat"),
        " — kol spa3 kansawbuh kayshhed 3la handasa shamilat f Shamal lMaghrib."
      ),
      p2: React.createElement(React.Fragment, null,
        "9wwatna : ",
        React.createElement("i", {className:"it"}, "kol ldawra"),
        " f yed wahda. Tassawwur, rkhsa, tanfid, istilam — muhawir wahid mn lawwal hetta l lakhir."
      ),
      p3: React.createElement(React.Fragment, null,
        "Nta f Tanja wla f Bariz, f Brixil wla f Muntryal — mashrou3k ",
        React.createElement("i", {className:"it"}, "kaytsir"),
        ", muwaththa9 w muttaba3 f wa9t ha9i9i mn fri9 tatiman bih 3a'ilat Tanja mn jilin."
      ),
      sig: "— MK Architects, Mohandes M3mari · Tanja.",
    },
    stats: [
      { n: 30,    label: "3am dyal lkhdma",   suffix: "" },
      { n: 340,   label: "Mashrou3 mkmmul",   suffix: "+" },
      { n: 220000,label: "Metr mrabba3 mbni", suffix: "+" },
      { n: 18,    label: "Takhassos m3mariya",suffix: "" },
    ],
    strip: { title_1: "Mashari3", title_2: "jdida", meta: "Ikhtiyar mn 2022 hetta 2024 f kamel lmamlaka." },
    gallery: {
      title_1: "Kol", title_2: "lmashari3",
      filters: { all: "Kolshi", archi: "Handasa", interior: "Dakhli", villa: "Villa", residence: "Résidence" },
      meta: "Ktar mn 25 mashrou3. 9lb bach tchuf kbira.",
    },
    ba: { title_1: "9bel", title_2: "b3d", meta: "Zla9 lmu2achir. B3d ltajrubat ma kayn ma fiha l'kalam." },
    timeline: { title_1: "Tlatin", title_2: "3am", meta: "Sit mahat shakkilat lmakatib." },
    ticker: ["Tanja", "Casa", "Rbat", "Marrakech", "Fes", "Tétouan", "Bariz", "Brixil", "Amsturdam", "Muntryal", "Dubay", "Madrid", "Assila"],
    market: {
      eyebrow: "Su9 l3qar f Tanja",
      title_1: "Lqitmar f Tanja :",
      title_2: "lara9am kayhdru.",
      desc: "Tanja hiya lmadina dial dinamisme f lMaghrib lArabi. Awwal mina f Ifriqiya wl Mutawasit, 9utb sina3i 3alami, numu dimugrafi musta9arr — l'usus l3aqariya mmumayyaza w la-ittijah yatas3ar.",
      highlights: [
        { n: "+43 %", label: "Irrtifa3 l'atman l'aqariya — Tanja 2021–2024" },
        { n: "115 Mrd",label: "Dirham hawwlat lMRE l lMaghrib f 2023" },
        { n: "Ra9m 1",  label: "Mina l'containers f Ifriqiya wl Mutawasit" },
        { n: "+1000",   label: "Sharika dawliya f Zone Franche Tanja" },
      ],
      chart1_title: "Tatawwur ta9dir lmetr mrabba3 skaniy",
      chart1_sub:   "Tanja — Manati9 prime",
      chart1_source:"Masdar: ANCFCC · IPAI, Bank Al-Maghrib",
      chart2_title: "Tahwilat MRE l lMaghrib",
      chart2_sub:   "Milyar dirham — 2019 hetta 2023",
      chart2_source:"Masdar: Bank Al-Maghrib, Rapport annuel 2023",
      sources: "Masadir: Bank Al-Maghrib · ANCFCC · Haut-Commissariat au Plan (HCP) · CRI Tanja-Titwaniya-Lhusima · Tanger Med · Ministère de l'Industrie.",
    },
    mre: {
      eyebrow: "Lmaghribt Saknin Barra",
      title_1: "Darekum f Tanja.",
      title_2: "Ntuma, fin ma ntuma.",
      desc: "Sakinin f Fransa, Beljika, Hulanda, Kanada wla lKhalij. Lmashrou3 dyalkum l3aqari f Tanja ysta7aq sharik mwuthu9 ydiru mn al-alif hetta lya - bla ma t9tdiru t3bru lbhar f kol joum3a korach.",
      stat1_n: "+45", stat1_l: "Mashrou3 livri l 3amlat MRE",
      stat2_n: "8",   stat2_l: "Biran dyal 3amlitna",
      stat3_n: "48h", stat3_l: "Wa9t rijou3 mdhman",
      cards: [
        { num:"01", title: "Muta3a usbu3iya bsswar wlvidiyu", desc: "Ta9rir mussawar kol usbu3: swar lwarcha, mqata3 vidyu, taqaddum kol lot. Tchufu kol marhala kannah ntu hadrin." },
        { num:"02", title: "Muhawir wahid dima mawjud",       desc: "Mohandes mkhassas lmashrou3kum. WhatsApp, mukalamat vidyu, email — belfrancawiya, l3arabiya wla ddarija." },
        { num:"03", title: "Tasiyir shamil mn al-alif l-lya",  desc: "Rkhsat lbna, ikhtiyr lmu9awwlin, muta3at l'ashghal, mura9abat ljawda, istilam l'a3mal. Ntuma t9ballu lmarahil lassasiya, w nahnu ndiru lba9i." },
        { num:"04", title: "Sarfiyat b'a9sat mwaththa9a",     desc: "Fluskum ma ykhurju 7etta bl-dalil lmussawar wa mwaththa9 3la tta9addum lhaqiqi. La daf3at mu9addama ghir mubrrara." },
        { num:"05", title: "Tansi9 tawthiqi w masrafi",        desc: "Kan3amlu m3a mu9adidkum wl-bank dyalkum f Tanja. Tahwilat, ruhun, 3uqud — kanrshidukum f kol khutwa idariya." },
        { num:"06", title: "Taslim 'miftah f yad'",            desc: "T7ttu charabtakum f dar kamla, nqiya, mwaththa9a khritta khritta. Daman 3ashri. Murafiqa ba3d ttaslim mashmulatun lssana lwwla." },
      ],
      cta: "Ana MRE — nahdar 3la lmashrou3 dyali",
    },

    /* ── Expertises DR ── */
    expertises: {
      eyebrow: "Khadamat dyalna",
      title_1: "Tlata takhassosat.",
      title_2: "3onwan wahad.",
      intro: "Handasa m3mariya, dakhli, istichara 3qariya — kolshi li kathtaj bach tkammal mashrou3 dyalek f lMaghrib, bla mufaja2at, m3a cabinet musta9il 3arif f lmihna mn 30 3am.",
      items: [
        {
          num: "01",
          title: "Handasa M3mariya",
          sub: "Skaniy · Sina3i · Tijari · Mrafiq 3amma",
          desc: "Villa, mujam3at skaniya, mbani sina3iya, mdrassat, fanadi9, 3imarat. Mn awwal khat hetta l akhir tashyit — cabinet wahad, mas2uliya wahida.",
          services: [
            "Makhtatat tassawwur w tanfid",
            "Dossier dyal rkhsat lbna",
            "Ikhtiyr lmu9awwlin w tansi9",
            "Muta3at lwarcha w mura9abat ljawda",
            "Istilam l'a3mal",
          ],
          cta: "Shuf lmashari3 →",
          href: "#projets",
          highlight: false,
        },
        {
          num: "02",
          title: "Handasa Dakhli",
          sub: "3la l9yas · Tacdid · Skan w mihana",
          desc: "Riyad, dupleks m3asir, lofts, ajna7a fundu9iya, salun istiqbal, show-rooms. Kansawbu dakhli kat3akkas huwiyat lmaskun w tts9a f lwaqt.",
          services: [
            "Tassawwur w makhtatat ltahyi2a",
            "Ikhtiyr lmawad w lathat w lathat",
            "Tacdid w tahwil kamil",
            "Muta3at a3mal ttahyi2a",
            "Diku nihay w i3dad",
          ],
          cta: "Shuf ldakhli →",
          href: "#interieur",
          highlight: false,
        },
        {
          num: "03",
          title: "Istichara w Murafa9a 3qariya",
          sub: "Shira · Jdawi · Mardudiya · Tadbir lmashrou3",
          desc: React.createElement(React.Fragment, null,
            "L9iti ard. Wajju-lik 3ard. Walakinn wash hiya lmawdi3 ssa7, taman ssa7, lmu9awwil lmwuthu9? Lbna w l'istithmar f lMaghrib kayhwaju ij-ra2at m3a9ada. ",
            React.createElement("strong", null, "Mn 30 3am kayn3rfu lmidan 7arfiyyan."),
            " Dawrna: n3zzabukum 3la lakhta2 lghalia w nkabbru l'istithmar dyalkum."
          ),
          services: [
            "Due diligence w ta7lil lard (russum 3qariya, ma3amalat lbna, lkharita ttawjihiya)",
            "Dirasa ljadwa lm3mariya w taqdir lmizaniya lmusta9il",
            "Istichara f l'istithmar l'ij-riy w ta7lil lmardudiya",
            "Musa3ada sa7ib lmashrou3 (ikhtiyr lmu9awwlin, ta7qi9 l3urud, mura9aba)",
            "Murafa9a idariya: rkhssat, CTC, istilam",
            "Ta9yim l3qarat lqayyima w ttash-khis tta9ni 9bal shira",
          ],
          cta: "Na7dar 3la mashrou3i →",
          href: "#rdv",
          highlight: true,
        },
      ],
    },

    rdv: {
      eyebrow: "Akhd Mawed",
      title_1: "Nahdru 3la",
      title_2: "lmashrou3 dyalek.",
      desc: "Awal li9a, hur w serri. 3amer lkaghit w ghadi nt9ablawk f 48 sa3a — f lMaghrib wla mn barra.",
      contact: { address: "Tanja, l'Maghrib", phone: "+212 6 XX XX XX XX", email: "contact@cabinet-marrakchi.ma", hours: "Tnin — Jum3a, 9–18" },
      addr_k: "3onwan", phone_k: "Tilifun", email_k: "Email", hours_k: "Sa3at",
      steps: ["Naw3", "Tabi3a", "Ta3aruf", "Tarikh", "Risala"],
      step_count: (i, n) => `Marhala ${i} / ${n}`,
      s1_title_1: "Ach", s1_title_2: "naw3 lmashrou3?", s1_sub: "Ikhtiyar wahed.",
      s1_opts: [
        { k: "archi",    label: "Handasa m3mariya", hint: "Bina jdid" },
        { k: "interior", label: "Dakhli",           hint: "Tahi2a" },
        { k: "both",     label: "Bjouj",            hint: "Mashrou3 kamel" },
        { k: "reno",     label: "Tarmim",           hint: "Kayn" },
      ],
      s2_title_1: "Ach", s2_title_2: "tabi3at lmashrou3?", s2_sub: "Bach n7aďru lli9a.",
      s2_opts: [
        { k: "villa",      label: "Villa / dar",      hint: "Sakan fardi" },
        { k: "residence",  label: "Résidence / mujam3",hint: "Jama3i" },
        { k: "industriel", label: "Mbna sina3i",       hint: "Usine, makhzan" },
        { k: "equipement", label: "Mrafiq 3amma",      hint: "Madrasa, 3iyada, fundu9" },
        { k: "bureau",     label: "Bureau / tijara",   hint: "Mihani" },
        { k: "autre",      label: "Akhar",             hint: "Yuhaddad" },
      ],
      s3_title_1: "Chkun", s3_title_2: "nta?", s3_sub: "Serri, 7it ghir l had ttalab.",
      f_name: "Smiya kamla", f_email: "Email", f_phone: "Tilifun",
      s4_title_1: "Imta", s4_title_2: "nt9ablu?", s4_sub: "Khtar tarikh, ghadi n2akkdu sa3a.",
      days: ["Tn","Tl","Ar","Km","Jm","Sb","A7"],
      months: ["Yanayer","Fébrayr","Mars","Abril","May","Yunyu","Yulyuz","Ghoucht","Chutanbir","Uktubar","Nuwanbir","Dujanbir"],
      s5_title_1: "Klma", s5_title_2: "akhira?", s5_sub: "Ilham, 9iyud, raghba. Kolshi kay3awen.",
      f_msg: "Lmessage dyalek (ikhtiyari)",
      recap: "Mulakhkhas", r_type: "Naw3", r_nature: "Tabi3a", r_contact: "Ta3aruf", r_date: "Tarikh", r_msg: "Risala",
      btn_next: "Tali", btn_back: "Rja3", btn_submit: "Sifet ttalab",
      success_t1: "Chukran,", success_t2: "nchoufouk 9rib.",
      success_p: "Ttalab dyalek wsel. Ghadi nt9ablawk f 48 sa3a — mn lMaghrib wla mn barra.",
      success_mark: "✓", none: "—",
    },
    footer: {
      title: "MK Architects — Tanja",
      desc: "Mohandes M3mari · Hay2a Watania Dyal Lmuhandissin, lMaghrib · Tasis 1998.",
      col1: "Lmakatib",  col1_links: ["Lfikra", "Falsafa", "Tarikh", "Contact"],
      col2: "Khadamat",  col2_links: ["Villa w Dar", "Mujam3at", "Mbani Sina3iya", "Mrafiq 3amma", "Dakhli"],
      col3: "Tab3",      col3_links: ["Instagram", "LinkedIn", "Pinterest", "Behance"],
      copyright: "© 2026 MK Architects. Jami3 l7u9u9 mahfuda.",
      credit: "Tasis 1998 · Tanja, lMaghrib",
    },
  },
};
